# Array

In [4]:
import numpy as np
x = [1,2,3,4,5]

y = np.array(x)
print(y)
print(type(y))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
y

array([1, 2, 3, 4, 5])

- User input array creation

In [10]:

list_user = []
for i in range(1,5):
    int_1 = int(input("Enter: "))
    list_user.append(int_1)
print(list_user) #list print

# np.array converts a list into an array
print(np.array(list_user))

Enter:  1
Enter:  2
Enter:  3
Enter:  4


[1, 2, 3, 4]
[1 2 3 4]


In [12]:
y

array([1, 2, 3, 4, 5])

In [14]:
# what is the dimension of y array

print(y.ndim)

1


In [17]:
# Create a 2D array
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)
print(arr2.ndim)

[[1 2 3 4]
 [5 6 7 8]]
2


In [18]:
# 3D Array

arr3 = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
print(arr3)
print(arr3.ndim)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
3


In [20]:
# create n dimensional array  eg. 10D
arrn = np.array([1,2,3,4], ndmin=10)
print(arrn)
print(arrn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


## Create Numpy using function

- array filled with 0, 1, empty, range of elements etc.


## zeros

In [23]:
import numpy as np
ar_zero = np.zeros(4)
# create zeros - x,y dimentional array
ar_zero1 = np.zeros((3,4))
print(ar_zero)
print(ar_zero1)



[0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## Ones

In [24]:
# create 1 d array of 4 elements
ar_ones = np.ones(4)
print(ar_ones)

[1. 1. 1. 1.]


## Empty

In [25]:
empty_arr = np.empty(4)
print(empty_arr)

[1. 1. 1. 1.]


## Array with Range

In [27]:
arr_range = np.arange(4)
print(arr_range)

[0 1 2 3]


## Array diagonal elements as 1

In [30]:
diag_arr = np.eye(3,3) #Create 3X3 Array of 2D with Diagonals as 1
print(diag_arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [31]:
# 3X5 diagonal array
diag_3x5_arr = np.eye(3,5)
print(diag_3x5_arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


## Create an Array with values that are spaced linearly in a specified interval

In [32]:
# create linspace array from 0 to 10 range containing 5 elements
arr_linspace = np.linspace(0,10, num= 5)
print(arr_linspace)

[ 0.   2.5  5.   7.5 10. ]


## Day 2- Creating numpy array with Random number

### Rand()


In [3]:
import numpy as np
arrray_rand = np.random.rand(4) #create 1D array consisting 4 values.
print(arrray_rand)

[0.38486649 0.44035231 0.19862152 0.26886419]


In [2]:
print("Hello Aditya")

Hello Aditya


In [8]:
# Create an array with 2 rows and 5 columns
# Create an array of the given shape and populate it with random samples
#  from a uniform distribution over [0, 1).

var_2x5 = np.random.rand(2,5)
print(var_2x5)

[[0.81905296 0.79841614 0.84791282 0.8379327  0.354932  ]
 [0.26844858 0.73070806 0.64773814 0.42577192 0.10737087]]


In [9]:
# randn() = generate random value close to zero, it may contain negative values too.

var_randn  = np.random.randn(5)
print(var_randn)

[ 1.54993734  0.47476002  0.9505484  -1.09700828  0.74756032]


## ranf()

In [14]:
var_ranf = np.random.ranf(4)
print(var_ranf)

[0.65785456 0.95955984 0.44956015 0.96960223]


## randint()

In [21]:
min, max, total_number = 5,20, 5
# generate 5 number between 5 to 20 
var_randint = np.random.randint(min,max, total_number)
print(var_randint)

[9 9 9 6 8]
