# Datatype in numpy arrays

In [16]:
import numpy as np
var_int64  = np.array([1,2,3,4])
print("Data Type ", var_int64.dtype)

Data Type  int64


In [17]:
var_float64 = np.array([1.0,1.2,1.3])
print(var_float64.dtype)

float64


In [18]:
"""
the 1 in u1 indicates 
that each value in the array takes up 1 byte of memory. 
Since it's unsigned, the range of values for u1 goes from 0 to 255 (2^8 - 1)
 because there are 256 possible combinations of 1s and 0s in a single byte.
"""

var_unsigned_1 = np.array(['a','b','c'])
print(var_unsigned_1.dtype)

<U1


In [19]:

var_unsigned_11 = np.array(['a','b','c',1,2,3,4])
print(var_unsigned_11.dtype)

<U21


### Convert datatype into another

In [20]:
x = np.array([1,2,3,4])
print(x.dtype)

int64


In [14]:
# Convert int64 into int8 by passing an argument called dtype with mode to convert
x = np.array([1,2,3,4], dtype= np.int8)
print(x.dtype)
print(x)

int8
[1 2 3 4]


In [15]:
# Convert int64 into float by passing an argument called dtype with string mode to convert
xf = np.array([1,2,3,4], dtype= "f")
print(xf.dtype)
print(xf)

float32
[1. 2. 3. 4.]


In [24]:
# Convert datatype through function
x_int = np.array([1,2,3,4])
x_float = np.float32(x_int)
print(x_int.dtype)
print(x_float.dtype)

print(x_int)
print(x_float)

int64
float32
[1 2 3 4]
[1. 2. 3. 4.]


### Convert the datatype using astype() function

In [28]:
x_var = np.array([1,2,3,4])
convert_astype = x_var.astype(float)
print(x_var)
print(x_var.dtype)
print(convert_astype)
print(convert_astype.dtype)

[1 2 3 4]
int64
[1. 2. 3. 4.]
float64
