In [1]:
import numpy as np

## Search Array function
- return the index of the searched array 
- use where keyword to search for an element.

In [4]:
var_a = np.array([1,2,3,4,2,5,6,7])
# search 2
x = np.where(var_a == 2)
even = np.where((var_a %2) == 0)

print(x)
print(even)

(array([1, 4]),)
(array([1, 3, 4, 6]),)


### Search Sorted Array

If you want to search for a specific value in a sorted NumPy array, you can use the numpy.searchsorted function. This function performs a binary search on the sorted array and returns the index where the specified value should be inserted to maintain the array's sorted order.

In [12]:
var_x = np.array([1,2,3,4,6,7])
x1 = np.searchsorted(var_x, 5)
x2 = np.searchsorted(var_x, [9,10,11], side="right")
print(x1)
print(x2)


4
[6 6 6]


In [15]:
# Sort array in ascending order

var_unsort = np.array([2,4,1,6,5])
var_sort = np.sort(var_unsort)
print(var_sort)

[1 2 4 5 6]


In [18]:
# Filter Array -Getting some elements from an existing array and creating new array out of them.

var_alpha = np.array(['a','b','d','c'])
fil = [True,False,True,True]

new_a = var_alpha[fil] #store all true elements of var_alpha

print(new_a)

['a' 'd' 'c']
