## Matrix in numpy

In [4]:
import numpy as np 

var = np.matrix([[1,2,3],[1,2,3]])
print(type(var))

<class 'numpy.matrix'>


In [7]:
# Matrix multiplication
var_a = np.matrix([[1,2],[1,2]])
var_b = np.matrix([[1,2],[1,2]])

# using dot function to multiply two matrix

print(var_a.dot(var_b))


[[3 6]
 [3 6]]


### Matrix functions
#### Transpose
* The transpose of a matrix is an operation that involves swapping the rows and columns of the matrix. If you have a matrix A with dimensions m x n, the transpose of A, denoted as ATAT, will have dimensions n x m.


In [15]:
var_a = np.matrix([[1,2],[1,2]])
var_b = np.matrix([[1,2],[1,2]])

print("before Transpose \n",var_a)

print("*"*30)


print("After Transpose \n",np.transpose(var_a))
print("After Transpose \n",var_a.T) #shortcut to transpose

before Transpose 
 [[1 2]
 [1 2]]
******************************
After Transpose 
 [[1 1]
 [2 2]]
After Transpose 
 [[1 1]
 [2 2]]


In [18]:
var_i = np.matrix([[1,2],[3,4]])

print(np.linalg.inv(var_i)) #inverse matrix

[[-2.   1. ]
 [ 1.5 -0.5]]


In [20]:
var_p = np.matrix([[1,2],[3,4]])

print(np.linalg.matrix_power(var_p, 2)) #power of 2
print(np.linalg.matrix_power(var_p, 0)) #power of 0
print(np.linalg.matrix_power(var_p, -2)) #power of -2

[[ 7 10]
 [15 22]]
[[1 0]
 [0 1]]
[[ 5.5  -2.5 ]
 [-3.75  1.75]]


In [22]:
var_d = np.matrix([[1,2],[3,4]])

print(np.linalg.det(var_d)) #determinate of matrix


-2.0000000000000004
