## Broadcasting in numpy

- Broadcasting in NumPy is a powerful feature that simplifies operations on arrays with different shapes. 
- It allows you to perform element-wise operations between arrays of different shapes and sizes without explicitly reshaping them. 
- Broadcasting becomes especially useful in scenarios where you want to avoid unnecessary memory usage and improve code readability.

In [2]:
import numpy as np 
# Why broadcasting? lets see this error

var1 = np.array([1,2,3,4])  #1D array with 4 elements
var2 = np.array([1,2,3])   # 1D array with 3 elements

print(var1+ var2)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [9]:
var_a = np.array([1,2,3])
var_b = np.array([[1],[2],[3]])
print(var_a.shape)
print(var_b.shape)
print()
print(var_a+var_b)
print((var_a+var_b).shape) #3x3

(3,)
(3, 1)

[[2 3 4]
 [3 4 5]
 [4 5 6]]
(3, 3)
