## Indexing and Slicing in numpy arrays

In [4]:
import numpy as np 

var_1d = np.array([9,8,7,6])
# index 8 

print(var_1d[1])
print(var_1d[-1]) #6
print(var_1d[1:]) #876

8
6
[8 7 6]


In [7]:
var_2d = np.array([[8,6,5],
                   [4,5,6]
                   ])
print(var_2d[1,1:])  #5,6
# print 8
print(var_2d[0,0])
print(var_2d[0,:2])  #8 and 6

[5 6]
8
[8 6]


In [71]:
var_3d = np.array([[[1,2],
                    [3,4],
                    [5,6]
                    ]])
print(var_3d.ndim)
# access 6 number
print(var_3d[0,2,1])
print(var_3d[0,1:,0]) # access 3 and 5
print(var_3d[0,(0,2),(1,1)]) # access 2 and 5
print(var_3d[0,0:,0]) # access 1,3,5
print("-"*30)


3
6
[3 5]
[2 6]
[1 3 5]
------------------------------
[[4]
 [6]]


### Slicing
- In NumPy, slicing is a powerful way to extract a portion of an array. 
- It allows you to create a view into the original array without copying the data. 
- NumPy slicing follows a similar syntax to Python lists.
- start:stop:step


In [84]:
var_sl = np.array([1,2,3,4,5,6,7])
print(var_sl[1:5]) #2,3,4,5
print(var_sl[1:5:2]) #2,4 ie, step 2 (even)
print(var_sl[7:0:-1]) #neg slice end to initial
print(var_sl[len(var_sl):0:-2]) #neg slice end to initial with step 2

[2 3 4 5]
[2 4]
[7 6 5 4 3 2]
[7 5 3]


In [94]:
var_2dd = np.array([[1,2,3,4,5],
                    [2,3,4,5,6],
                    [2,3,4,5,6]])
# print 3,4,5,6 of 2nd row
print(var_2dd[1,1:])

# print 3,4 of 2nd and 3rd row
print(var_2dd[1:,1:3])

# access 3,4 of row1 and 45 of 3rd row
print(var_2dd[0:2:1,2:4])

[3 4 5 6]
[[3 4]
 [3 4]]
[[3 4]
 [4 5]]
