## Arithmatic Operation in numpy array

In [2]:
import numpy as np
# add 1D array with 3

var = np.array([1,2,3,4])
var_add = var + 3
print(var_add)

[4 5 6 7]


In [3]:
# add 1D array with another 1D

var_a = np.array([1,2,3,4])
var_b = np.array([1,2,3,4])
var_add = var_a + var_b
print(var_add)

[2 4 6 8]


In [8]:
# Similar Operation using other operators Eg. Multiply by 3
var_to_mul = np.array([12,23,45,5])
print(var_to_mul *3)

# print(var_to_mul /3)  #Divide
print(var_to_mul %2) #Modulus for getting remainder


[ 36  69 135  15]
[0 1 1 1]


In [9]:
# Using add function

var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

print(np.add(var1,var2))

[2 4 6 8]


## 2D Array

In [15]:
var_2d_a = np.array([[1,2,3,4],[1,2,3,4]])
var_2d_b = np.array([[1,2,3,4],[1,2,3,4]])

print(np.add(var_2d_a,var_2d_b))
print(np.multiply(var_2d_a,var_2d_b))
print("Reciprocal \n",np.reciprocal(var_2d_a))

[[2 4 6 8]
 [2 4 6 8]]
[[ 1  4  9 16]
 [ 1  4  9 16]]
Reciprocal 
 [[1 0 0 0]
 [1 0 0 0]]
