# Shape and Reshape in numpy

In [9]:
import numpy as np

var = np.array([[1,2,3,4],[1,2,3,4]])

print(var)
print()
print(var.shape)  #2 rows and 4 columns

[[1 2 3 4]
 [1 2 3 4]]

(2, 4)


In [14]:
# create 4 dimensional array
var1 = np.array([1,2,3,4], ndmin=4)
print(var1)
print(var1.ndim)
# What is the shape
print(var1.shape)
# '''
# (1, 1, 1, 4) here 4 dim split as initial 3 are rows and last is column
# '''


[[[[1 2 3 4]]]]
4
(1, 1, 1, 4)


## Reshape

In [21]:
array_1d = np.array([1,2,3,4,5,6])  #1D array
x = array_1d.reshape(3,2)  #3 rows and 2 columns  [2D array]
print(array_1d)
print(x)

print(array_1d.ndim) #number of dimensions
print(x.ndim)

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]
1
2


In [25]:
var_temp3d = np.array([[[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]]])

convert_3d = var_temp3d.reshape(3,3,2) #3D array with 3*3*2 = 18 Elements but 3 rows and 3 columns
print(convert_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]


In [28]:
# reconvert 3d into 1D

one_d = convert_3d.reshape(-1)
print(one_d)
print("One Dimensional array ",one_d.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
One Dimensional array  1
