## Numpy Array Iteration

In [2]:
import numpy as np 
var_a = np.array([1,0,7,2,4])
print(var_a)

for i in var_a:
    print(i)


[1 0 7 2 4]
1
0
7
2
4


In [7]:
# iterating though a 2D Arrray
var_2d = np.array([[1,2,3,4], 
                   [23,45,23,25]])
print(var_2d.ndim) #2D Array
print()

for j in var_2d:
    print(j)

print("-"*10)

for k in var_2d:
    for l in k:
        print(l)


2

[1 2 3 4]
[23 45 23 25]
----------
1
2
3
4
23
45
23
25


In [13]:
# 3D Array

var_3d = np.array([[[1,2,3],
                    [3,2,1],
                    [4,5,6]]])
# print(var_3d.ndim) #3D

# iterate 3D array
for i in var_3d:
    for j in i:
        for k in j:
            print(k)
print("-"*10)
# access specific element - eg 2nd row 2nd column (2)
print(var_3d[0,1,1])


1
2
3
3
2
1
4
5
6
----------
2


### nditr function to iterate through array

In [18]:
var_3d2 = np.array([[[9,8,7,6],[1,2,3,4]]])
# print(var_3d2.ndim)
# for i in np.nditer(var_3d2):
#     print(i)
# store earlier data in buffer and convert into strings
for i in np.nditer(var_3d2, flags=['buffered'], op_dtypes=['S']):
    print(i)


b'9'
b'8'
b'7'
b'6'
b'1'
b'2'
b'3'
b'4'


In [19]:
# print index number along with iteration

var_3d3 = np.array([[[9,8,7,6],[1,2,3,4]]])
# similar to enumerate
for i,d in np.ndenumerate(var_3d3):
    print(i,d)

(0, 0, 0) 9
(0, 0, 1) 8
(0, 0, 2) 7
(0, 0, 3) 6
(0, 1, 0) 1
(0, 1, 1) 2
(0, 1, 2) 3
(0, 1, 3) 4
