## Arithmatic Functions of numpy

In [5]:
import numpy as np

var_ = np.array([1,2,3,4,5,3,2])
print(np.min(var_))
print(np.max(var_))

# argmin - min position
print(np.argmin(var_))
print(np.argmax(var_))

1
5
0
4


In [10]:

var_2d = np.array([[2,1,3],[9,5,6]])
print(np.max(var_2d))
# np.argmin(var, axis) = axis works 0 for column and 1 for rows
print(np.min(var_2d, axis=1)) #rows wise search
print(np.min(var_2d, axis=0)) #column wise search

9
[1 5]
[2 1 3]


In [11]:
print(np.sqrt(var_2d))

[[1.41421356 1.         1.73205081]
 [3.         2.23606798 2.44948974]]


In [13]:
# sin and cos value

var_sin_cos = np.array([1,2,3])
print(np.sin(var_sin_cos))
print(np.cos(var_sin_cos))

[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]


In [14]:
# cumulative sum
# Each element in the cumulative_sum array is the sum of all the elements in the original array up to that index.
x_cumsum = np.array([1,2,3])
print(np.cumsum(x_cumsum))

[1 3 6]
