## Numpy Functions
#### Shufle

In [6]:
import numpy as np 
var_a = np.array([1,2,3,4,5])
np.random.shuffle(var_a)

print(var_a)

[1 5 4 3 2]


### Unique

In [8]:
var_data = np.array([1,2,3,1,2,4,6,3,2])

# x = np.unique(var_data)
x = np.unique(var_data, return_index=True, return_counts=True) #if you want to see index
print(x)

(array([1, 2, 3, 4, 6]), array([0, 1, 2, 5, 6]), array([2, 3, 2, 1, 1]))


### Resize

In [9]:
var2 = np.array([1,2,3,4,5])
y = np.resize(var2,(2,3))
print(y)

[[1 2 3]
 [4 5 1]]


### Flaten

In [17]:
# y is already a 2D array
print(y.flatten(order="C")) #converted into 1D array.

[1 2 3 4 5 1]


### Ravel 
is a function that returns a flattened, one-dimensional array containing the same elements as the input array. It returns a view of the original array whenever possible; 

In [18]:
print(np.ravel(y))

[1 2 3 4 5 1]


In [28]:
var_data = np.array([1,2,3,4])
# x= np.insert(var_data,2, 40) #2nd index value 40
x = np.append(var_data, [2,3] )
print(x)

delete_va = np.delete(var_data,0)
print(delete_va)

[1 2 3 4 2 3]
[2 3 4]
