## Join and Split Function in numpy array

In [3]:
import numpy as np 

In [8]:
var_a = np.array([12,3,43,23])
var_b = np.array([1,2,3,4])

ar = np.concatenate((var_a,var_b))
print(ar)

ar2 = np.concatenate((var_a,var_b), axis=0)
print(ar2)

[12  3 43 23  1  2  3  4]
[12  3 43 23  1  2  3  4]


In [14]:
var_c = np.array([12,3,43,23])
var_d = np.array([1,2,3,4])

c_new = np.stack((var_c,var_d), axis=1)
d_new = np.hstack((var_c,var_d)) #row
d_new2 = np.vstack((var_c,var_d)) #column
d_new3 = np.dstack((var_c,var_d)) #height

print(c_new)
print()
print(d_new)
print(d_new2)
print(d_new3)


[[12  1]
 [ 3  2]
 [43  3]
 [23  4]]

[12  3 43 23  1  2  3  4]
[[12  3 43 23]
 [ 1  2  3  4]]
[[[12  1]
  [ 3  2]
  [43  3]
  [23  4]]]


### Split Array

In [22]:
# 1D array Split

var_1d = np.array([1,2,3,4,5,6])
print(var_1d)

print("*"*10)
var_new_split_array = np.array_split(var_1d, 3) #3 split array
print(var_new_split_array)

[1 2 3 4 5 6]
**********
[array([1, 2]), array([3, 4]), array([5, 6])]


In [27]:
# Splitting 2D array
var_2d = np.array([[1,2],[3,4],[5,6]])
print(var_2d)

print("*"*10)
var_2d_split = np.array_split(var_2d, 3)
print(var_2d_split)

[[1 2]
 [3 4]
 [5 6]]
**********
[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]
